from __future__ import annotations

from pathlib import Path
from typing import Iterable

import pandas as pd



def build_report(
    report_path: Path,
    summary: pd.DataFrame,
    drift: pd.DataFrame,
    rag_gain: pd.DataFrame,
    error_table: pd.DataFrame,
    figure_paths: Iterable[Path],
    run_name: str,
) -> None:
    figure_html = "\n".join(
        f'<div class="figure"><img src="{path.as_posix()}" alt="{path.stem}" /><p>{path.stem}</p></div>'
        for path in figure_paths
    )

    html = f"""
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{run_name} - Quantum API Drift Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 2rem; color: #1f2937; }}
    h1, h2 {{ margin-top: 1.4rem; }}
    table {{ border-collapse: collapse; width: 100%; margin-bottom: 1.2rem; font-size: 0.92rem; }}
    th, td {{ border: 1px solid #d1d5db; padding: 0.5rem; text-align: left; }}
    th {{ background: #f3f4f6; }}
    .grid {{ display: grid; grid-template-columns: 1fr; gap: 1rem; }}
    .figure img {{ max-width: 100%; border: 1px solid #e5e7eb; }}
    .note {{ background: #eff6ff; padding: 0.8rem; border-left: 4px solid #2563eb; }}
  </style>
</head>
<body>
  <h1>{run_name}</h1>
  <p class="note">This report is automatically generated by Quantum API Drift Lab. It summarizes execution outcomes, pass rates, drift-break-rate, mitigation gains, and error taxonomy.</p>

  <h2>Summary metrics</h2>
  {summary.to_html(index=False, escape=False)}

  <h2>Cross-version drift</h2>
  {drift.to_html(index=False, escape=False)}

  <h2>Mitigation effectiveness</h2>
  {rag_gain.to_html(index=False, escape=False)}

  <h2>Error taxonomy</h2>
  {error_table.to_html(index=False, escape=False)}

  <h2>Figures</h2>
  <div class="grid">
    {figure_html}
  </div>
</body>
</html>
""".strip()
    report_path.write_text(html, encoding="utf-8")
